### ISSUE TITLE
Prerequisites question

### ISSUE THREAD

**Issue by pjmolina** [LionWeb-io/property-demo#22]
Are prerequisites limited to exact versions?

> - Java 11 installed and set as current JDK
> - MPS 2021.1 installed

I guess, some how. Tested with latest Java 21 & MPS 2023.2 fails in the following way:

```bash
$ ./gradlew setup

FAILURE: Build failed with an exception.

* What went wrong:
Could not open cp_settings generic class cache for settings file 'D:\explore\property-demo\settings.gradle' (...\.gradle\caches\8.1.1\scripts\eld8xz5n9lrhz5w1h54n46r9e).
> BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 65
...
BUILD FAILED in 464ms
``` 

I will try downgrading Java to 11.

**Comment by pjmolina** [comment]
Confirmed: needed **exact** versions of both:
- [Java 11](https://www.oracle.com/es/java/technologies/javase/jdk11-archive-downloads.html)
- [MPS 2021.1.4](https://www.jetbrains.com/es-es/mps/download/previous.html)

**Comment by enikao** [comment]
MPS in general doesn't react kindly on different dependency versions. Unless you're looking for an adventure, you should stick to the described versions.
